# https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
url: https://haeger.me
title: haeger.me
description: Personal website of Alexander Häger
author: Alexander Häger

exclude: ["Gemfile", "Gemfile.lock", "README.md", "CNAME"]

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
